### ISSUE TITLE
Can you provide some documentation to use it in another application?

### ISSUE THREAD

**Issue by saan1984** [adamschwartz/chrome-tabs#10]
Please provide some information on installation and usage of this tab in an application.

**Comment by niutech** [comment]
+1 for API reference.

**Comment by rmrio** [comment]
yes, please!

**Comment by mateusdemboski** [comment]
+1 for API reference.

**Comment by licongmu** [comment]
+1 for API reference!!!
i am not able to use it totally!!

**Comment by adamschwartz** [comment]
Here’s a [jsFiddle](https://jsfiddle.net/adamschwartz/w7vmbavd/) to get you started and a [more complicated one](https://jsfiddle.net/adamschwartz/kqokoopj/show/light/) for fun.
