### ISSUE TITLE
Outstanding Work!

### ISSUE THREAD

**Issue by jaswrks** [adamschwartz/chrome-tabs#18]
@adamschwartz Thanks for all of your work on this project!

FYI: I forked your project into a [new variation of Chrome Tabs](https://github.com/src-works/chrome-tabs), and I built an  [NPM module](https://www.npmjs.com/package/x-chrome-tabs).

**Comment by adamschwartz** [comment]
Thanks @jaswrks! Love where you took it! Nice job. Anywhere I can see an Electron app using the tabs?

**Comment by jaswrks** [comment]
I'm glad to hear that. Thank you @adamschwartz.
Yes, take a look here: https://jaswsinc.github.io/slick/

**Comment by adamschwartz** [comment]
Very cool! Looks native! I’m impressed :)

**Comment by jaswrks** [comment]
Thanks! Yes, it really does. Your work to mimic Chrome was really fantastic. That part was all you.

**Comment by adamschwartz** [comment]
Thanks! :1st_place_medal:

**Comment by acllm** [comment]
@jaswrks 
Is there a tutorial about how to use [this npm](https://www.npmjs.com/package/x-chrome-tabs) module in a react project?

**Comment by ashishBharadwaj** [comment]
@imac-beep  did you find a way to integrate it with react?
