### ISSUE TITLE
is possible add button new tab on tab

### ISSUE THREAD

**Issue by ridwanskaterock** [adamschwartz/chrome-tabs#21]
is possible add button new tab on tab like chrome browser

![image](https://cloud.githubusercontent.com/assets/9270445/25070018/e4dc73a4-22bb-11e7-8ceb-5b828923c771.png)

chroome 

![image](https://cloud.githubusercontent.com/assets/9270445/25070023/22537ed0-22bc-11e7-9030-8e921bac1724.png)

if possible where is documentation or example

thanks

**Comment by adamschwartz** [comment]
Hey @ridwanskaterock, this is definitely something we’d like to add. I believe @dansiej started on a PR https://github.com/adamschwartz/chrome-tabs/pull/20 which may be a good reference for you. For updates on the addition of this feature request, please see https://github.com/adamschwartz/chrome-tabs/issues/22. Thanks!

Closing as dup of https://github.com/adamschwartz/chrome-tabs/issues/22.
