### ISSUE TITLE
Chrome-Tab-Content Positioning

### ISSUE THREAD

**Issue by sathyaprakash94** [adamschwartz/chrome-tabs#27]
Hi there ,

Tab content set to the full width using,
`$('.chrome-tab-content').width(document.documentElement.clientWidth);`

but the tab content start from the left position 0 of corresponding parent element.

I tried to fix the position of the tab content starts from and take entire space to visible the current tab using,

```
if ($('.chrome-tab-current').offset().left !== 69) {
      var vleft = $('.chrome-tab-current').children().eq(4).children().offset().left;
      $('.chrome-tab-current').children().eq(4).children().css({ 'position': 'absolute', 'left': '-' + (vleft - 50) + 'px', 'top': '26px', 'z-index': '1' });
  } else {
           console.log('Offset left not matched.');
  }
```
Now the positioning issue solved by setting the positioning manually. But when closing the prev tabs, the position of sibling tabs went outside of left due to -posision applied to fix the full width.

I hope you understand. If Im not clear, pls check the image posted earlier.

**Comment by adamschwartz** [comment]
Closing as this is a duplicate of https://github.com/adamschwartz/chrome-tabs/issues/26

**Comment by sathyaprakash94** [comment]
Hi look after the chrome browser tabs. The content of the tab takes full width and other tab contents not visible. Also the contents not overlapping with another tab contents when close the tabs. Only the current tab or active tab contents only visible to the user.

I request you to enhance the plugin feature.

**Comment by adamschwartz** [comment]
Closing as this is a duplicate of https://github.com/adamschwartz/chrome-tabs/issues/26

**Comment by sathyaprakash94** [comment]
Hi thanks for your reply #26 

Placing the tab content outside of chrome-tab is not usable.
