### ISSUE TITLE
Chrome tab content feature

### ISSUE THREAD

**Issue by sathyaprakash94** [adamschwartz/chrome-tabs#28]
Hi look after the chrome browser tabs. The content of the tab takes full width and other tab contents not visible. Also the contents not overlapping with another tab contents when close the tabs. Only the current tab or active tab contents only visible to the user.

I request you to enhance the plugin feature.

**Comment by adamschwartz** [comment]
Duplicate https://github.com/adamschwartz/chrome-tabs/issues/27
