### ISSUE TITLE
Stackable? aka Tab Stacking

### ISSUE THREAD

**Issue by EC-O-DE** [adamschwartz/chrome-tabs#32]
Could these tabs bend to being stacked? Tab stacking or Tab grouping are the buzz words.

See:
https://www.youtube.com/watch?v=drCAiTSAYdc

Also:
https://www.youtube.com/watch?v=eaaYp8544bs

Would be a nice feature indeed! :)

**Comment by adamschwartz** [comment]
Your example shows this feature being part of part Opera’s tab implementation and not Chrome’s. As such it falls outside of the scope of this project. Please feel free to fork the project and add it there!
