### ISSUE TITLE
Transfrom attribute

### ISSUE THREAD

**Issue by samdenty** [adamschwartz/chrome-tabs#35]
What's the use for the `transfrom` attribute? I thought it was a typo (as my tslint pointed out) and so renamed it to `transform`, which had no effect on Chrome (but firefox accepts it, which led to some  debugging).

It doesn't seem to be a proper HTML attribute as per spec, and leaving it out doesn't seem to have any effect either
https://github.com/adamschwartz/chrome-tabs/blob/c7a0123f65d0f776f783c2280cfab9ff68477c97/index.html#L28

**Comment by adamschwartz** [comment]
Thanks! Just a typo. https://github.com/adamschwartz/chrome-tabs/commit/082012137daa250a7d7d241ea276ec27d84c011a
