### ISSUE TITLE
Tabs depth and change style for multi tabs.

### ISSUE THREAD

**Issue by prpanto** [adamschwartz/chrome-tabs#38]
Firefox: v61.0.1
Chrome: v67

Just look around for errors and bugs and this time I find some more stuff for fix.  Just look every time when open new tab and how the "style" change to Chrome tabs. The letters must hide and tabs must styled as triangle after x (number of tabs e.g. x = 40 or 50 tabs).

chrome-tabs:
![chrome-tabs-issue-2](https://user-images.githubusercontent.com/19821270/42620136-c38989d8-85c2-11e8-88b7-44b4eb6d06c2.gif)

vs 

Chrome:
![origin-chrome-tabs](https://user-images.githubusercontent.com/19821270/42620154-ce5eb112-85c2-11e8-8bf1-67d749cc8ee4.gif)

Must fix depth and style for tabs.
![screenshot_2](https://user-images.githubusercontent.com/19821270/42620663-4055aaa4-85c4-11e8-8569-910dacd8c2ee.png)
![screenshot_3](https://user-images.githubusercontent.com/19821270/42620868-e5f7be66-85c4-11e8-8ef7-4c5cad264aed.png)

**Comment by adamschwartz** [comment]
This should be greatly improved with the latest design. The clipping is still an issue, but I am considering that out of scope as implementers are allowed to specify a tab minimum width, the behavior is unspecified.
