### ISSUE TITLE
Unselected tab does not active on click for drag and drop and passes underground.

### ISSUE THREAD

**Issue by prpanto** [adamschwartz/chrome-tabs#39]
Firefox: v61.0.1
Chrome: v67

![chrome-tabs-issue-3](https://user-images.githubusercontent.com/19821270/42621152-b71b9698-85c5-11e8-880a-8f50f5652eb7.gif)

**Comment by adamschwartz** [comment]
![chrome-tabs-background-time-reorder](https://user-images.githubusercontent.com/154613/42651721-35329758-85de-11e8-8182-f10af7d442d7.gif)

Although it seems a bit odd, that’s actually the behavior of Google Chrome.
