### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by tistudios** [adamschwartz/chrome-tabs#44]
Link doesn't work - is there an alternative way to access the files

**Comment by adamschwartz** [comment]
Github took down all of my website hosted on GH pages today with no warning for no apparent reason. I’ve been contacting support but they haven’t gotten back to me yet. I’ll keep you posted. I’m sorry for the inconvenience.

**Comment by adamschwartz** [comment]
Github fixed the issue. Sorry for the inconvenience.
