### ISSUE TITLE
How to add iframe content into tab dynamically

### ISSUE THREAD

**Issue by afsalcodehack** [adamschwartz/chrome-tabs#47]
How to add iframe content into tab dynamically

**Comment by sathyaprakash94** [comment]
Hi,
In this way you can add the iframe content.
`chromeTabs.addNewTab($chromeTabsExampleShell, {
						favicon: cssname,
						title: "Menu Name",
						menulink: "Iframe Src Link",
						data: {
							timeAdded: +new Date()
						}
					});`

**Comment by afsalcodehack** [comment]
Uncaught ReferenceError: $chromeTabsExampleShell is not defined

**Comment by sathyaprakash94** [comment]
What version you are using?

**Comment by afsalcodehack** [comment]
i am not sure about the version just download from this repo two days back i hope it will be the latest one

**Comment by adamschwartz** [comment]
Duplicate https://github.com/adamschwartz/chrome-tabs/issues/50
