### ISSUE TITLE
Issues with AMD

### ISSUE THREAD

**Issue by tHBp** [adamschwartz/chrome-tabs#49]
There are lot of issues while calling the library using RequireJS style AMD.

I have created a [pull request](https://github.com/adamschwartz/chrome-tabs/pull/48) which fixes this by using the UMD pattern.

**Comment by adamschwartz** [comment]
Thanks for bumping this. I’ll take a look at the PR as soon as I can. I appreciate your help.

**Comment by adamschwartz** [comment]
@tHBp this should be all set now. Thanks again for your help with this.
