### ISSUE TITLE
Bug when creating many tabs

### ISSUE THREAD

**Issue by mathieurivest** [adamschwartz/chrome-tabs#5]
Bug when filling tab bar with many tabs. It seems like after a point, tabs are just created out of view.

![image](https://f.cloud.github.com/assets/4664198/2231311/b93cb7fa-9b0e-11e3-8874-d87ed3a68c40.png)

**Comment by LasagnaAndroid** [comment]
+1

**Comment by adamschwartz** [comment]
What alternative behavior would you want? I can think of quite a few, but none stand out to me as clear winners:

- Allow the tab bar to scroll horizontally
- Enforce a maximum number of tabs and minimum tab bar width necessary to display this max
- Show multiple rows of tabs
- Show a dropdown to access extra/hidden tabs, similar to how the Chrome extension button works
  ![screen shot 2015-04-23 at 5 57 37 pm](https://cloud.githubusercontent.com/assets/154613/7308418/48714a62-e9e2-11e4-9a51-70a891f01d42.png)
- Tab stacking of some sort
  ![screen shot 2015-04-23 at 6 00 48 pm](https://cloud.githubusercontent.com/assets/154613/7308474/bacd1776-e9e2-11e4-94fe-33fa0716dd1e.png)

----------------------------------

It should be noted that the latest Chrome (42.0.2311.90) on Mac OS X hides overflowing tabs roughly the same way we do.

![screen shot 2015-04-23 at 5 50 02 pm](https://cloud.githubusercontent.com/assets/154613/7308320/6e28c704-e9e1-11e4-8e77-4a69c6da04ed.png)

This window has 16 tabs and yet only 10 are shown. Even selected 11th tab is not even shown. I vaguely remember a time when Chrome used to show arrows to let you scroll the tab bar, but I guess that’s gone.

**Comment by adamschwartz** [comment]
Closing for now. Please provide a specific suggestion for improvement and we’ll reopen. Thx

**Comment by adriansalgadoa** [comment]
I just tested and when you reach a limit it starts creating them out of view (which is the correct behavior) but the last tab gets cut in half.

![captura de pantalla 2015-04-30 10 05 09](https://cloud.githubusercontent.com/assets/3248837/7413326/12b03052-ef21-11e4-892a-24110383d75e.png)

I think the dropdown is a great idea, although it isn't chrome's "natural" behavior.
