### ISSUE TITLE
Add the content window to each tab like chrome browser

### ISSUE THREAD

**Issue by sathyaprakash94** [adamschwartz/chrome-tabs#50]
Hi,
I like to add the mock-browser-content inside each tab created instead of having the mock-browser-content statically standing outside of chrome tabs created. 
But styling issues happening when trying to add inside the tabs. It would be helpful if you add that functionality.

**Comment by adamschwartz** [comment]
This project focuses on the visual design and interaction of the actual tabs themselves. Designing an application to which makes use of these tabs falls outside of the scope of this project.
