### ISSUE TITLE
Does not work in IE 

### ISSUE THREAD

**Issue by MohammadYaaser** [adamschwartz/chrome-tabs#52]
All functions like add, dark theme, remove background tabs and close icons doesn't show up
![image](https://user-images.githubusercontent.com/31729450/57520336-05dac980-733b-11e9-941e-12bdd62b0340.png)

**Comment by ShlomiRex** [comment]
Can confirm.
Don't think it should be available on internet explorer. It's deprecated browser.

**Comment by adamschwartz** [comment]
We won’t be supporting IE.
