### ISSUE TITLE
Detect Reordering

### ISSUE THREAD

**Issue by pjebs** [adamschwartz/chrome-tabs#54]
When the tabs are reordered, how can we detect the new order?

**Comment by adamschwartz** [comment]
Awesome question. As you may have seen, there is a [`tabReorder` event](https://github.com/adamschwartz/chrome-tabs/blob/a978533c33600361976734c0869036ebe51d139b/js/chrome-tabs.js#L355) you can listen to.

That event passes you `{ tabEl, originIndex, destinationIndex }`, which allows you to get the element that moved and what its position in the list was/is now.

If you’re interested in getting the entire list of tabs when a reorder occurs, you’ll first want to make sure that your tabs have unique ids, which you can ensure by passing an id to `addTab({ id: generateUnique() })` when creating your tabs. Then in your handler for the `tabReorder` event just iterate through the tabs and grab all of their `data-tab-id` attribute values.

I hope this helps!
