### ISSUE TITLE
Chrome Tabs Stacked VERTICALLY?

### ISSUE THREAD

**Issue by mywebguytaylor** [adamschwartz/chrome-tabs#56]
I am looking for a chrome extension which allows me to automatically sort and group Chrome tabs...VERTICALLY. (not horizontally). I have just spent 10 hours trialing every tab organizer extension I could find, and none of them have this feature. for example, if I have 10 tabs open "domain1.com" it will nicely organize them into a vertical bucket, drop down etc, is that possible yet with Chrome?  If you find something like this, can you message me on skype?  SMARTCHOICEWEB

**Comment by adamschwartz** [comment]
Hey @mywebguytaylor you may want to check out this [Chrome extension](https://chrome.google.com/webstore/detail/vertical-tabs/pddljdmihkpdfpkgmbhdomeeifpklgnm?hl=en-US) (although I haven’t evaluated it myself so beware). Additionally, you may want to check out Firefox which has [a number of extensions](https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=vertical%20tabs) offering this sort of functionality.

That being said, this project is about implementing a tab design inside a browser page (or Electron app, etc.), not replacing a browser’s native implementation of tabs. Closing as invalid.

**Comment by mywebguytaylor** [comment]
Adam, that one, VERTICAL TABS, does group them by domain, it just put all
the tab vertically in side bar...
