### ISSUE TITLE
setAttribute value not triggering

### ISSUE THREAD

**Issue by ajai06** [adamschwartz/chrome-tabs#59]
hi, I am trying to integrate ui tour guide in chrome-tabs. for that, I tried with a package named 'ngx-joyride' which required an attribute name called "joyrideStep = 'name'".so while initing chrome tabs for all the chrome elements I manually append an attribute `element.setAttributeNS(null,"joyrideStep", tab_id) `. while consoling chrome elements, attribute value updated but tour guide not showing in any of the chrome tabs. I also tried with a different tour package got the same result. not able to find where this issue is happening. 

   ```let all_left_panel_tabs = document.querySelectorAll(".left-panel-tab .chrome-tab");
        all_left_panel_tabs.forEach((element) => {
            
            let tab_id = element.getAttribute('data-tab-id');
            element.setAttributeNS(null,"joyrideStep", tab_id);
            console.log(element);
          })
        this.joyrideService.startTour(
            { steps: ['backup','bookmarks','rvclean','workspace','settings','comments',],
              showCounter: true,
              themeColor: '#5a5e60'

            } // Your steps order
          )

"@angular/cli": "^6.2.9"
"chrome-tabs": "^5.4.0"     


 thanks !.

**Comment by adamschwartz** [comment]
Unfortunately this type of question falls outside the scope of maintenance of the library itself, which is what this Github repo is for. I’d recommend looking into StackOverflow or another community which accepts general programming questions. Best of luck!
