### ISSUE TITLE
Prevent closing some tabs (based on a condtion)

### ISSUE THREAD

**Issue by busaeed** [adamschwartz/chrome-tabs#65]
I would like to prevent closing some tabs based on a condition.

```
      el.addEventListener('tabRemove', ({ detail }) => {
        //check if the tab is closable or not
        let isClosable = document.getElementById("tabc_" + detail.tabEl.id.slice(5)).contentWindow.isClosable();
        if (!isClosable) {
          event.preventDefault(); //I'm trying to prevent the tab from being closed here if isClosable == false
        }
        //remove its iframe
        document.getElementById("tabc_" + detail.tabEl.id.slice(5)).remove();
      });
```

**Comment by adamschwartz** [comment]
That won’t work with the library’s current design unfortunately, as the tab is removed before the event is emitted:

https://github.com/adamschwartz/chrome-tabs/blob/a978533c33600361976734c0869036ebe51d139b/js/chrome-tabs.js#L232-L245

However, this is potentially something that could be changed.

For now, if you have control over the library code, your best bet would be to add such a condition to the `removeTab()` method itself.
