### ISSUE TITLE
bower and npm?

### ISSUE THREAD

**Issue by stevemao** [adamschwartz/chrome-tabs#7]

**Comment by tobiasoberrauch** [comment]
:+1:

**Comment by dan-petty** [comment]
:+1:

**Comment by adamschwartz** [comment]
PR welcome :stuck_out_tongue:

**Comment by adamschwartz** [comment]
https://github.com/adamschwartz/chrome-tabs/commit/c116a0f774b985ebb8da102c034e29498259b752

v1.0.0 is now published: https://www.npmjs.com/package/chrome-tabs
