### ISSUE TITLE
um, so what even is this? I want trapezoid tabs back in my chromium

### ISSUE THREAD

**Issue by calexil** [adamschwartz/chrome-tabs#70]
how do I even use this?

**Comment by adamschwartz** [comment]
This is an HTML/JS/CSS implementation of Chrome-style tabs. It cannot be used to replace Chrome’s own tabs (unless you were to roll your own Chromium-based browser that used something Electron as the shell to render the tabs in HTML).

As for the trapezoidal-style versions of yore, see: https://github.com/adamschwartz/chrome-tabs/blob/gh-pages/older-versions.md
